  [build]
  publish = "./"
  command = "echo 'Building with Netlify Includes'"

[build.environment]
  NETLIFY_BUILD_USE_INCLUDES = "true"
  
  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Method = ["GET"] }

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
