[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.125.0" # hoặc bản mới nhất
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Method = ["GET"] }

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
