[build]
  command = "echo 'Building with Netlify Includes'"
  publish = "./"
  functions = "emails"  # Thư mục chứa functions email

[build.environment]
  NETLIFY_BUILD_USE_INCLUDES = "true"

# Cấu hình functions cho mọi môi trường
[functions]
  included_files = [
    "./emails/**/*.js",  # Chỉ include file JS để tối ưu
    "./emails/**/*.json" # Các file hỗ trợ nếu có
  ]

# Redirect rules (giữ nguyên của bạn)
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Method = ["GET"] }
