backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/posts"
    extension: html  # <-- Quan trọng: Tạo file .html thay vì .md
    format: html     # <-- Định dạng nội dung là HTML
    slug: "{{slug}}"  # URL sẽ là /test.html (không cần thêm .html ở đây)
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Content", widget: "markdown" }  # Vẫn dùng Markdown để nhập liệu

  - name: "pages"
    label: "Pages"
    create: true
    files:
      - name: "about"
        file: "src/pages/about.html"  # <-- Đổi thành .html
        label: "About Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }

      - name: "contact"
        file: "src/pages/contact.html"  # <-- Đổi thành .html
        label: "Contact Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "email", label: "Email", widget: "string" }

  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        file: "src/data/settings.json"
        label: "General Settings"
        fields:
          - { name: "site_name", label: "Site Name", widget: "string" }
