backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"    # Nơi lưu ảnh trong repo
public_folder: "/uploads"         # Đường dẫn công khai của ảnh

collections:
  - name: "posts"                 # Tên collection (không dấu cách)
    label: "Blog Posts"            # Nhãn hiển thị trong CMS
    folder: "content/posts"        # Nơi lưu bài viết Hugo
    create: true                   # Cho phép tạo bài viết mới
    slug: "{{slug}}"               # Định dạng tên file
    format: "frontmatter"          # Hugo dùng front matter YAML/TOML/JSON
    extension: "md"                # Lưu bài viết dưới dạng Markdown
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
