backend:
  name: git-gateway
  branch: main

media_folder: "static/images/alda/blog" # Thư mục lưu trữ hình ảnh
public_folder: "/images/alda/blog" # Đường dẫn công khai cho hình ảnh

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/posts"
    extension: html
    format: html
    slug: "{{slug}}"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Content", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    create: true
    files:
      - name: "about"
        file: "src/pages/about.html"
        label: "About Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }

      - name: "contact"
        file: "src/pages/contact.html"
        label: "Contact Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "email", label: "Email", widget: "string" }

  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        file: "src/data/settings.json"
        label: "General Settings"
        fields:
          - { name: "site_name", label: "Site Name", widget: "string" }
