backend:
  name: git-gateway
  branch: main

# Thư mục lưu media
media_folder: "images/blog"
public_folder: "/images/blog"

# Cấu hình collections
collections:
  - name: "blog" 
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Aldahub"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

# Cấu hình giao diện
locale: 'en'
show_preview_links: false
display_url: https://aldahub.com
logo_url: https://aldahub.com/images/logo.png
